{
 "title": "Main dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "server", "query": "artillery-api" },
   {
    "name": "container",
    "query": "exchange-api-1, exchange-api-2, exchange-api-3, exchange-cadvisor-1, exchange-grafana-1, exchange-graphite-1,  exchange-nginx-1, exchange_bbox_1"
   }
  ]
 },
 "panels": [
  {
   "title": "Movimientos netos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.currency.*.net, 3)"
    }
   ]
  },
  {
   "title": "Volumen de movimientos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.currency.*.volume, 3)"
    }
   ]
  },
  {
   "title": "Neto vs Volumen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.currency.*.volume, 3, 4)"
    },
    {
     "target": "aliasByNode(stats.gauges.currency.*.net, 3, 4)"
    }
   ]
  },
  {
   "title": "Scenarios launched (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$server.scenarioCounts.*)"
    }
   ]
  },
  {
   "title": "Requests state (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$server.errors.*), 'Errored')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.200, 'Completed')"
    },
    {
     "target": "alias(stats.gauges.$server.pendingRequests, 'Pending')"
    },
    {
     "target": "alias(stats.gauges.$server.codes.429, 'Limited')"
    }
   ]
  },
  {
   "title": "Response time (client-side)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.max, 'Upper')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.median, 'Median')"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.$container.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.$container.memory_working_set, 34359738368), 'Memory')"
    }
   ]
  }
 ]
}